apiVersion: v1
kind: Pod
metadata:
  name: myapi
  labels:
    name: myapi
spec:
  containers:
  - name: api
    image: sanamakk/myapi:1.0.0
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 8000
